# Generated by Django 3.2.7 on 2021-09-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_time_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='value',
        ),
    ]
